### ISSUE TITLE
Random failure in podman deployment

### ISSUE THREAD

**Issue by nka11** [breard-r/acmed#102]
Hello,

I deployed ACMED in a podman environment.
It works well and generates a cert at launch if it does not exist. Unfortunately it
fails  when trying to determine renew period with randomness...
```
[2023-11-10T16:23:39Z TRACE acmed::main_event_loop] Adding certificate: nginx_default_rsa4096
[2023-11-10T16:23:39Z DEBUG acmed::certificate] certificate "nginx_default_rsa4096": checking for renewal (identifiers: )
[2023-11-10T16:23:39Z TRACE acmed::storage] certificate "nginx_default_rsa4096": testing file path: /var/certs/nginx_default_rsa4096.pk.pem
[2023-11-10T16:23:39Z TRACE acmed::storage] certificate "nginx_default_rsa4096": testing file path: /var/certs/nginx_default_rsa4096.crt.pem
[2023-11-10T16:23:39Z TRACE acmed::storage] certificate "nginx_default_rsa4096": reading file "/var/certs/nginx_default_rsa4096.crt.pem"
[2023-11-10T16:23:39Z DEBUG acmed::certificate] certificate "nginx_default_rsa4096": certificate expires in 89 days (30 days delay)
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rand-0.8.5/src/rng.rs:134:9:
cannot sample empty range
stack backtrace:
   0:     0x55c70a28324c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c70a28324c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c70a28324c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c70a28324c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55c70a132c3c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x55c70a132c3c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x55c70a27f1ce - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x55c70a283034 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55c70a283034 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55c70a289ce3 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x55c70a289a2f - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x55c70a28a1d6 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x55c70a28a0b4 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  13:     0x55c70a288e46 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55c70a289e72 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x55c70a058893 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x55c70a058923 - core::panicking::panic::hd907d42d09324a32
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
  17:     0x55c70a0ce237 - acmed::main_event_loop::MainEventLoop::run::{{closure}}::h5010543ffbdf423e
  18:     0x55c70a0d2fde - acmed::inner_main::{{closure}}::h516ef2296ac78188
  19:     0x55c70a0d173c - acmed::main::hc37f30cf3252ae80
  20:     0x55c70a06c26a - std::sys_common::backtrace::__rust_begin_short_backtrace::h54e4788db0d8db37
  21:     0x55c70a06c691 - std::rt::lang_start::{{closure}}::hf3a7d1b7532d3c6f
  22:     0x55c70a27922b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc4f8a3f5ada78c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  23:     0x55c70a27922b - std::panicking::try::do_call::he5f117a9e13dadde
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  24:     0x55c70a27922b - std::panicking::try::h2f3af9afce3a0443
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  25:     0x55c70a27922b - std::panic::catch_unwind::h6d6c387f38ef05ea
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  26:     0x55c70a27922b - std::rt::lang_start_internal::{{closure}}::h6ca09d5905711415
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  27:     0x55c70a27922b - std::panicking::try::do_call::ha9fd18ea06654a4b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  28:     0x55c70a27922b - std::panicking::try::hda5c2a4432362341
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  29:     0x55c70a27922b - std::panic::catch_unwind::h440f731b142bc235
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  30:     0x55c70a27922b - std::rt::lang_start_internal::hc0b4e50f058f62ce
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  31:     0x55c70a06c686 - std::rt::lang_start::hfb1428766cb0010e
  32:     0x7f506606409b - __libc_start_main
  33:     0x55c70a063ada - _start
  34:                0x0 - <unknown>
Aborted
exit code: 134
```

**Comment by nka11** [comment]
Setting a value to the global option random_early_renew solves the problem.

```
[global]
random_early_renew = "1w"
```

some verifications could be implemented and prevent random time calculation if the random period value is 0

Source & analyse from the small talk opened by @Salah-Eddine-Harnoufi in the dependency lib : https://github.com/rust-random/rand/issues/1091

**Comment by breard-r** [comment]
Thank you for the report, I will get it fixed soon.

**Comment by breard-r** [comment]
It should now be fixed. Before releasing a new version, could you confirm me that ACMEd does no longer crash please?
